# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

COUNTRIES = (
 (u'africa', _(u'Africa')),
 (u'argentina', _(u'Argentina')),
 (u'asia', _(u'Asia')),
 (u'australia', _(u'Australia')),
 (u'austria', _(u'Austria')),
 (u'belarus', _(u'Belarus')),
 (u'belgium', _(u'Belgium')),
 (u'brazil', _(u'Brazil')),
 (u'bulgaria', _(u'Bulgaria')),
 (u'chile', _(u'Chile')),
 (u'china', _(u'China')),
 (u'colombia', _(u'Colombia')),
 (u'concacaf', _(u'Concacaf')),
 (u'costarica', _(u'Costa Rica')),
 (u'croatia', _(u'Croatia')),
 (u'cyprus', _(u'Cyprus')),
 (u'czechia', _(u'Czechia')),
 (u'denmark', _(u'Denmark')),
 (u'egypt', _(u'Egypt')),
 (u'england', _(u'England')),
 (u'equador', _(u'Equador')),
 (u'estonia', _(u'Estonia')),
 (u'eurocups', _(u'Eurocups')),
 (u'finland', _(u'Finland')),
 (u'france', _(u'France')),
 (u'germany', _(u'Germany')),
 (u'greece', _(u'Greece')),
 (u'holland', _(u'Holland')),
 (u'hungary', _(u'Hungary')),
 (u'iceland', _(u'Iceland')),
 (u'ireland', _(u'Ireland')),
 (u'israel', _(u'Israel')),
 (u'italy', _(u'Italy')),
 (u'japan', _(u'Japan')),
 (u'korea', _(u'Korea')),
 (u'latvia', _(u'Latvia')),
 (u'lithuania', _(u'Lithuania')),
 (u'mexico', _(u'Mexico')),
 (u'norway', _(u'Norway')),
 (u'olympic', _(u'Olympic')),
 (u'paraguay', _(u'Paraguay')),
 (u'peru', _(u'Peru')),
 (u'poland', _(u'Poland')),
 (u'portugal', _(u'Portugal')),
 (u'romania', _(u'Romania')),
 (u'russia', _(u'Russia')),
 (u'saudi_arabia', _(u'Saudi Arabia')),
 (u'scotland', _(u'Scotland')),
 (u'serbia', _(u'Serbia')),
 (u'singapore', _(u'Singapore')),
 (u'slovakia', _(u'Slovakia')),
 (u'slovenia', _(u'Slovenia')),
 (u'southafrica', _(u'South Africa')),
 (u'southamerica', _(u'South America')),
 (u'spain', _(u'Spain')),
 (u'sweden', _(u'Sweden')),
 (u'switzerland', _(u'Switzerland')),
 (u'turkey', _(u'Turkey')),
 (u'uae', _(u'UAE')),
 (u'ukraine', _(u'Ukraine')),
 (u'uruguay', _(u'Uruguay')),
 (u'usa', _(u'USA')),
 (u'venezuela', _(u'Venezuela')),
 (u'wales', _(u'Wales')),
 (u'worldcup', _(u'World Cup')),
)
