FIXTURES = {
    'albania': ['KategoriaSuperiore',
                 'League1',
                 'League2-GroupA',
                 'League2-GroupB'],
     'algeria': ['Division-1', 'Division2'],
     'andorra': ['2aDivisio', 'PrimeraDivision'],
     'angola': ['Girabola'],
     'argentina': ['Apertura',
                   'ArgentinoA',
                   'ArgentinoB',
                   'Clausura',
                   'PrimBMetro',
                   'primerab',
                   'PrimeraCMetro',
                   'PrimeraDMetro'],
     'armenia': ['FirstLeague', 'PremierLeague'],
     'aruba': ['DivisiondiHonor'],
     'australia': ['A-League',
                   'Brisbane',
                   'CapitalTerritory',
                   'NewSouthWales',
                   'NorthernNsw',
                   'Nothern',
                   'Queensland',
                   'SouthAustralian',
                   'Tasmania-North',
                   'Tasmania-South',
                   'Victorian',
                   'WesternAustralia'],
     'austria': ['1-Liga',
                 'Bundesliga',
                 'Cup',
                 'Landesliga-Burgenland',
                 'Landesliga-Karnten',
                 'Landesliga-Niederosterreich',
                 'Landesliga-Oberosterreich',
                 'Landesliga-Salzburg',
                 'Landesliga-Steiermark',
                 'Landesliga-Tirol',
                 'Landesliga-Vorarlbergliga',
                 'Landesliga-Wien',
                 'Regionalliga-Mitte',
                 'Regionalliga-Ost',
                 'Regionalliga-West'],
     'azerbaidjan': ['BirinciDasta', 'PremyerLiqasi'],
     'bahrain': ['PremierLeague'],
     'bangladesh': ['BLeague'],
     'barbados': ['PremierLeague'],
     'belarus': ['Division1', 'Division2', 'PremierLeague'],
     'belgium': ['cup',
                 'Divison3-GroupA',
                 'Divison3-GroupB',
                 'ProLeague',
                 'Promotion-GroupA',
                 'Promotion-GroupB',
                 'Promotion-GroupC',
                 'Promotion-GroupD',
                 'Provincial-Antwerpen',
                 'Provincial-Brabant',
                 'Provincial-Hainaut',
                 'Provincial-Liege',
                 'Provincial-Limburg',
                 'Provincial-Luxembourg',
                 'Provincial-Namur',
                 'Provincial-Oost-Vlaanderen',
                 'Provincial-West-Vlaanderen',
                 'SecondDivision'],
     'belize': ['PremierLeague'],
     'bermuda': ['PremierLeague'],
     'bhutan': ['ADivision'],
     'bolivia': ['PrimeraDivision'],
     'bosnia': ['1Liga-FBiH', '1Liga-RS', 'PremierLiga'],
     'botswana': ['PremierLeague'],
     'brazil': ['Acreano',
                'Alagoano',
                'Amapaense',
                'Amazonense',
                'Baiano1',
                'Baiano2',
                'Brasiliense',
                'CampeonatoNordeste',
                'Capixaba',
                'Carioca1-TacaGuanabara',
                'Carioca1-TacaRio',
                'Carioca2',
                'Catarinense',
                'Cearense',
                'Cearense2',
                'Cup',
                'Gaucho1',
                'Gaucho2',
                'Goiano',
                'Maranhense',
                'Matogrossense',
                'Mineiro1',
                'Mineiro2',
                'Paraense',
                'Paraibano',
                'Paranaense1',
                'Paranaense2',
                'PaulistaA1',
                'PaulistaA2',
                'PaulistaA3',
                'Pernambucano',
                'Piauiense',
                'Potiguar',
                'Rondoniense',
                'Roraimense',
                'Sergipano',
                'SerieA',
                'SerieB',
                'SerieC',
                'SerieD',
                'SulMatogrossense',
                'Tocantinense'],
     'brunei': ['PremierLeague'],
     'bulgaria': ['APFG',
                  'BPFG-East',
                  'BPFG-West',
                  'VAFG-Northeast',
                  'VAFG-Northwest',
                  'VAFG-Southeast',
                  'VAFG-Southwest'],
     'cambodia': ['PremierLeague'],
     'cameroon': ['EliteOne'],
     'canada': ['CSL', 'PCSL'],
     'chile': ['Primera', 'PrimeraB'],
     'china': ['LeagueOne', 'SuperLeague'],
     'chinese_taipei': ['NationalLeague'],
     'colombia': ['Apertura', 'Clausura', 'PrimeraB'],
     'costa_rica': ['Apertura', 'Clausura', 'LigadeAscenso'],
     'croatia': ['2HNL', '3HNL-Istok', '3HNL-Jug', '3HNL-Zapad', 'cup', 'HNL'],
     'cyprus': ['1-division', 'Division2', 'Division3'],
     'czechia': ['Cup',
                 'CzechLiga',
                 'Liga2',
                 'Liga3-CFL',
                 'Liga3-MSFL',
                 'Liga4-DivisionA',
                 'Liga4-DivisionB',
                 'Liga4-DivisionC',
                 'Liga4-DivisionD',
                 'Liga4-DivisionE'],
     'denmark': ['1stDivision',
                 '2ndDivision-East',
                 '2ndDivision-West',
                 'Denmarksserien-Group1',
                 'Denmarksserien-Group2',
                 'Denmarksserien-Group3',
                 'SuperLiga'],
     'ecuador': ['apertura', 'clausura', 'PrimeraB'],
     'egypt': ['PremierLeague',
               'SecondDivison-Group1',
               'SecondDivison-Group2',
               'SecondDivison-Group3'],
     'el_salvador': ['PrimeraDivision'],
     'england': ['BlueSquareNorth',
                 'BlueSquareSouth',
                 'CarlingCup',
                 'Championship',
                 'Conference',
                 'FACup',
                 'FATrophy',
                 'FLTrophy',
                 'LeagueOne',
                 'LeagueTwo',
                 'NonLeagueDivOne-IsthmianNorth',
                 'NonLeagueDivOne-IsthmianSouth',
                 'NonLeagueDivOne-NorthernNorth',
                 'NonLeagueDivOne-NorthernSouth',
                 'NonLeagueDivOne-SouthernCentral',
                 'NonLeagueDivOne-SouthernSW',
                 'NonLeaguePremier-Isthmian',
                 'NonLeaguePremier-Northern',
                 'NonLeaguePremier-Southern',
                 'PremierLeague'],
     'estonia': ['Esiliiga', 'Meistriliiga'],
     'eurocups': ['champleague', 'europaleague', 'euro_qualification'],
     'faroe_islands': ['1Delid', 'Formuladeildin'],
     'fiji': ['NationalFootballLeague'],
     'finland': ['Kakkonen-LohkoA',
                 'Kakkonen-LohkoB',
                 'Kakkonen-LohkoC',
                 'Veikkausliiga',
                 'Ykkonen'],
     'france': ['CFA-GroupA',
                'CFA-GroupB',
                'CFA-GroupC',
                'CFA-GroupD',
                'CFA2-GroupA',
                'CFA2-GroupB',
                'CFA2-GroupC',
                'CFA2-GroupD',
                'CFA2-GroupE',
                'CFA2-GroupF',
                'CFA2-GroupG',
                'CFA2-GroupH',
                'Cup',
                'LeagueCup',
                'Ligue1',
                'Ligue2',
                'National'],
     'friendly': ['intl_friendly'],
     'gabon': ['ChampionnatD1'],
     'georgia': ['PirveliLiga', 'UmaglesiLiga'],
     'germany': ['3Liga',
                 'Bundesliga',
                 'Bundesliga2',
                 'Cup',
                 'Oberliga-Baden-Wurttemberg',
                 'Oberliga-Bayern',
                 'Oberliga-Bremen',
                 'Oberliga-Hamburg',
                 'Oberliga-Hessen',
                 'Oberliga-Niedersachsen',
                 'Oberliga-Nordost-Nord',
                 'Oberliga-Nordost-Sud',
                 'Oberliga-NRW',
                 'Oberliga-Schleswig-Holstein',
                 'Oberliga-Sudwest',
                 'Regionalliga-Nord',
                 'Regionalliga-Sud',
                 'Regionalliga-West'],
     'ghana': ['PremierLeague'],
     'greece': ['BEthiniki',
                'CEthniki-Notios',
                'CEthniki-Voreios',
                'cup',
                'SuperLeague'],
     'grenada': ['PremierDivision'],
     'guadeloupe': ['DivisionDHonneur'],
     'guatemala': ['LigaNacional', 'PrimeraDivision'],
     'haiti': ['ChampionnatNational'],
     'holland': ['cup',
                 'EersteDivisie',
                 'Eredivisie',
                 'Topklasse-Saturday',
                 'Topklasse-Sunday'],
     'honduras': ['LigaNacional'],
     'hong_kong': ['Hkfa1stDivision', 'Hkfa2ndDivision'],
     'hungary': ['Cup',
                 'NBI',
                 'NbII-East',
                 'NbII-West',
                 'NbIII-Alfold',
                 'NbIII-Bakony',
                 'NbIII-Drava',
                 'NbIII-Duna',
                 'NbIII-Matra',
                 'NbIII-Tisza'],
     'iceland': ['1DelidKarla', '2DelidKarla', 'Urvalsdeild'],
     'india': ['ILeague'],
     'indonesia': ['SuperLiga'],
     'intl': ['AFCChallengeCup',
              'AFCChampionsLeague',
              'AFCCup',
              'ASEANCup',
              'AsianCup',
              'CAFChampionsLeague',
              'CAFConfederationsCup',
              'ConcacafGoldCup',
              'ConfederationsCup',
              'CopaAmerica',
              'CopaSudamericana',
              'CupOfNations',
              'Libertadores',
              'O-League'],
     'iran': ['AzadeganLeague-GroupA', 'AzadeganLeague-GroupB', 'PremierLeague'],
     'iraq': ['IraqiLeague-North', 'IraqiLeague-South'],
     'ireland': ['1stDivision', 'faicup', 'PremierLeague'],
     'israel': ['LigaLeumit', 'LigatAl'],
     'italy': ['Cup',
               'SerieA',
               'SerieB',
               'SerieC1-A',
               'SerieC1-B',
               'SerieC2-A',
               'SerieC2-B',
               'SerieC2-C'],
     'ivory_coast': ['Ligue1'],
     'jamaica': ['PremierLeague'],
     'japan': ['Cup', 'J-League', 'J2-League', 'J3League'],
     'jordan': ['League'],
     'kazakhstan': ['1stDivision', 'PremierLeague'],
     'korea': ['K-League', 'K2League'],
     'kuwait': ['Division1', 'PremierLeague'],
     'latvia': ['1Liga', 'Virsliga'],
     'lebanon': ['League'],
     'libya': ['PremierLeague'],
     'lithuania': ['1Lyga', 'ALyga'],
     'luxembourg': ['NationalDivision'],
     'macedonia': ['FirstLeague', 'SecondLeague'],
     'malaysia': ['PremierLeague', 'SuperLeague'],
     'malta': ['FirstDivision', 'PremierDivision'],
     'mexico': ['Apertura', 'Clausura', 'PrimeraA'],
     'moldova': ['DivisiaA', 'NationalDivision'],
     'montenegro': ['DrugaLiga', 'PrvaLiga'],
     'morocco': ['GNEF1', 'GNEF2'],
     'namibia': ['PremierLeague'],
     'nepal': ['ADivision'],
     'new_zealand': ['PremierLeague'],
     'nicaragua': ['1aDivision'],
     'nigeria': ['PremierLeague'],
     'northern_ireland': ['Championship1', 'IFAPremiership'],
     'norway': ['2Divisjon-Avdeling-1',
                '2Divisjon-Avdeling-2',
                '2Divisjon-Avdeling-3',
                '2Divisjon-Avdeling-4',
                'Adeccoligaen',
                'cup',
                'Eliteserien'],
     'oman': ['League'],
     'pakistan': ['PremierLeague'],
     'panama': ['PrimeraDivision'],
     'paraguay': ['Apertura', 'Clausura', 'DivisionIntermedia'],
     'peru': ['PrimeraDivision', 'SegundaDivision'],
     'poland': ['Division2',
                'Ekstraklasa',
                'IILiga-East',
                'IILiga-West',
                'PolandCup'],
     'portugal': ['Cup',
                  'Division2',
                  'IIDivisao-Centro',
                  'IIDivisao-Norte',
                  'IIDivisao-Sul',
                  'PortugueseLiga'],
     'qatar': ['League2', 'StarsLeague'],
     'romania': ['LigaI',
                 'LigaII-Seria1',
                 'LigaII-Seria2',
                 'LigaIII-Seria1',
                 'LigaIII-Seria2',
                 'LigaIII-Seria3',
                 'LigaIII-Seria4',
                 'LigaIII-Seria5',
                 'LigaIII-Seria6'],
     'russia': ['1-division',
                '2Division-Center',
                '2Division-East',
                '2Division-South',
                '2Division-Ural-Povolzhye',
                '2Division-West',
                'Cup',
                'PremierLeague'],
     'san_marino': ['Campionato'],
     'saudi_arabia': ['Division1', 'SaudiProfessionalLeague'],
     'scotland': ['Division1', 'Division2', 'Division3', 'FACup', 'PremierLeague'],
     'senegal': ['Ligue1'],
     'serbia': ['PrvaLiga',
                'SrpskaLiga-Belgrade',
                'SrpskaLiga-East',
                'SrpskaLiga-Vojvodina',
                'SrpskaLiga-West',
                'SuperLiga'],
     'singapore': ['SLeague'],
     'slovakia': ['Cup', 'IILiga-Vychod', 'IILiga-Zapad', 'ILiga', 'SuperLiga'],
     'slovania': ['1-SNL', 'cup'],
     'slovenia': ['2SNL'],
     'south_africa': ['PremierLeague'],
     'spain': ['Cup',
               'Primera',
               'Segunda',
               'SegundaB-Group1',
               'SegundaB-Group2',
               'SegundaB-Group3',
               'SegundaB-Group4',
               'Tercera-Group1',
               'Tercera-Group10',
               'Tercera-Group11',
               'Tercera-Group12',
               'Tercera-Group13',
               'Tercera-Group14',
               'Tercera-Group15',
               'Tercera-Group16',
               'Tercera-Group17',
               'Tercera-Group18',
               'Tercera-Group2',
               'Tercera-Group3',
               'Tercera-Group4',
               'Tercera-Group5',
               'Tercera-Group6',
               'Tercera-Group7',
               'Tercera-Group8',
               'Tercera-Group9'],
     'sudan': ['PremierLeague'],
     'surinam': ['Hoofdklasse'],
     'sweden': ['Allsvenskan', 'Division1-Norra', 'Division1-Sodra', 'Superettan'],
     'switzerland': ['ChallengeLeague', 'Cup', 'SuperLeague'],
     'syria': ['1stDivision'],
     'thailand': ['PremierLeague'],
     'trinidad_and_tobago': ['TnTProLeague'],
     'tunisia': ['Ligue1'],
     'turkey': ['Cup', 'LigA', 'LigB-Beyaz', 'LigB-Kirmizi', 'SuperLig'],
     'uae': ['Division1', 'PremierLeague'],
     'ukraine': ['Cup',
                 'PershaLiga',
                 'PremierLeague',
                 'SecondLeague-GroupA',
                 'SecondLeague-GroupB'],
     'uruguay': ['Apertura', 'Clausura', 'SegundaDivision'],
     'usa': ['Cup', 'MLS', 'PDL', 'USL1', 'USL2'],
     'uzbekistan': ['OliyLiga'],
     'venezuela': ['PrimeraDivision', 'SegundaDivision'],
     'vietnam': ['VLeague'],
     'wales': ['FACup',
               'FeederLeagues-CymruAlliance',
               'FeederLeagues-WelshLeagueDivision1',
               'PremierLeague'],
     'worldcup': ['ClubWorldCup',
                  'wc_qualification_africa',
                  'wc_qualification_asia',
                  'wc_qualification_concacaf',
                  'wc_qualification_europe',
                  'wc_qualification_oceania',
                  'wc_qualification_southamerica',
                  'WorldCup'],
     'yemen': ['League']
 }
